apiVersion: v1
kind: ConfigMap
metadata:
  name: "monitoring-config-overrides"
  namespace: "kyma-installer"
  labels:
    installer: overrides
    kyma-project.io/installation: ""
    component: monitoring
data:
  global.alertTools.credentials.slack.channel: "${KYMA_ALERTS_CHANNEL}"
  global.alertTools.credentials.slack.apiurl: "${KYMA_ALERTS_SLACK_API_URL}"
  prometheus-istio.envoyStats.sampleLimit: "8000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    kyma-project.io/installation: ""
    component: dex
data:
  connectors: |
    - type: github
      id: github
      name: GitHub
      config:
        clientID: ${GITHUB_INTEGRATION_APP_CLIENT_ID}
        clientSecret: ${GITHUB_INTEGRATION_APP_CLIENT_SECRET}
        redirectURI: ${DEX_CALLBACK_URL}
        orgs:
        - name: kyma-project
